### ISSUE TITLE
Sends wrong data when selecting empty path

### ISSUE THREAD

**Issue by joabakk** [tkurki/pebble-signalk#1]
Nice app @tkurki !

One thing I noticed is that if I select heading and then an empty path such as VMG, it displays the heading value and knots, in this case 207 knots.

**Comment by tkurki** [comment]
What do you mean by _empty path_?

**Comment by joabakk** [comment]
A path with no value. I may be mistaken

**Comment by tkurki** [comment]
Hmm. The hierarchy of values to pick from is populated from paths that have a value, so I don't see how that happens.

Do you have a log file to replicate this with?

**Comment by joabakk** [comment]
Using plaka.log and selecting boat speed --> shows 4.4 knots
then selecting heading --> shows 4.4 degrees. It may be my watch. Closing
